# Here all datasets properties and other things
root_dir: ".."
raw_data_path: "${root_dir}/data/0_raw"
meta_data_path: "${root_dir}/data/1_meta"

datasets:
  stanford_cars:
    urls: ["https://www.kaggle.com/datasets/jutrera/stanford-car-dataset-by-classes-folder"]
    google_drive_ids: {}
  car_connection:
    urls: []
    google_drive_ids: {
      "https://drive.google.com/open?id=1TQQuT60bddyeGBVfwNOk6nxYavxQdZJD": "carconnection.rar"
    }
  comp_cars:
    urls: ["https://www.kaggle.com/datasets/renancostaalencar/compcars/download?datasetVersionNumber=1"]
    google_drive_ids: {}

meta_infos:
  stanford_cars:
    annotations_path: "${raw_data_path}/stanford_cars"
    output_annotations_path: "${meta_data_path}/stanford_cars.csv"
  comp_cars:
    annotations_path: "${raw_data_path}/comp_cars"
    output_annotations_path: "${meta_data_path}/comp_cars.csv"
